package com.suray.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Test implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.key
     *
     * @mbg.generated
     */
    private Integer key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test
     *
     * @mbg.generated
     */
    private Integer test;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.key
     *
     * @return the value of test.key
     *
     * @mbg.generated
     */
    public Integer getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.key
     *
     * @param key the value for test.key
     *
     * @mbg.generated
     */
    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test
     *
     * @return the value of test.test
     *
     * @mbg.generated
     */
    public Integer getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test
     *
     * @param test the value for test.test
     *
     * @mbg.generated
     */
    public void setTest(Integer test) {
        this.test = test;
    }
}